name: Setup Azure Authentication

on:
  workflow_dispatch:
    inputs:
      azure_creds:
        description: 'Azure credentials JSON'
        required: true

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Parse Azure credentials
      id: creds
      run: |
        echo '${{github.event.inputs.azure_creds}}' > creds.json
        echo "CLIENT_ID=$(jq -r .clientId creds.json)" >> $GITHUB_ENV
        echo "CLIENT_SECRET=$(jq -r .clientSecret creds.json)" >> $GITHUB_ENV
        echo "TENANT_ID=$(jq -r .tenantId creds.json)" >> $GITHUB_ENV
        echo "SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)" >> $GITHUB_ENV
        rm creds.json

    - name: Install dependencies
      run: npm install

    - name: Check GH_PAT
      run: |
        echo "==================== DEBUG INFO ===================="
        echo "Is GH_PAT secret configured? ${{ secrets.GH_PAT != '' }}"
        echo "================================================="
        
        if [ "${{ secrets.GH_PAT }}" = "" ]; then
          echo "ERROR: GH_PAT secret is not set in repository secrets"
          echo "Please add it in Settings > Secrets and variables > Actions"
          exit 1
        fi

    - name: Run setup script
      env:
        AZURE_CLIENT_ID: ${{env.CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{env.CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{env.TENANT_ID}}
        AZURE_SUBSCRIPTION_ID: ${{env.SUBSCRIPTION_ID}}
      run: |
        echo "Setting up Azure authentication..."
        node setup-azure-auth.js "${{ secrets.GH_PAT }}"

    - name: Validate Azure Configuration
      run: |
        echo "Validating Azure Function configuration..."
        
        # Check for in-process settings
        inproc_setting=$(az functionapp config appsettings list \
          --name ${{ env.BACKEND_APP_NAME }} \
          --resource-group ${{ env.BACKEND_RG }} \
          --query "[?name=='FUNCTIONS_INPROC_NET8_ENABLED']")
        
        if [ ! -z "$inproc_setting" ]; then
          echo "Removing in-process settings..."
          az functionapp config appsettings delete \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.BACKEND_RG }} \
            --setting-names FUNCTIONS_INPROC_NET8_ENABLED
        fi

        # Configure for Hot Chocolate v14 and isolated worker
        az functionapp config appsettings set \
          --name ${{ env.BACKEND_APP_NAME }} \
          --resource-group ${{ env.BACKEND_RG }} \
          --settings \
            FUNCTIONS_WORKER_RUNTIME=dotnet-isolated \
            WEBSITE_LOAD_USER_PROFILE=1 \
            HC_MAX_REQUEST_SIZE=1048576 \
            WEBSITE_WEBSOCKETS_ENABLED=true

        # Verify configuration
        runtime=$(az functionapp config appsettings list \
          --name ${{ env.BACKEND_APP_NAME }} \
          --resource-group ${{ env.BACKEND_RG }} \
          --query "[?name=='FUNCTIONS_WORKER_RUNTIME'].value" -o tsv)
        
        if [ "$runtime" != "dotnet-isolated" ]; then
          echo "Error: Function app not configured for isolated worker process"
          exit 1
        fi

        echo "Configuration validated successfully"
