name: Setup Azure Authentication

on:
  workflow_dispatch:
    inputs:
      azure_creds:
        description: 'Azure credentials JSON'
        required: true

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Parse Azure credentials
      id: creds
      run: |
        echo "::add-mask::${{github.event.inputs.azure_creds}}"
        CREDS=''${{github.event.inputs.azure_creds}}''
        echo "CLIENT_ID=$(echo $CREDS | jq -r .clientId)" >> $GITHUB_ENV
        echo "CLIENT_SECRET=$(echo $CREDS | jq -r .clientSecret)" >> $GITHUB_ENV
        echo "TENANT_ID=$(echo $CREDS | jq -r .tenantId)" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Run setup script
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        AZURE_CLIENT_ID: ${{env.CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{env.CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{env.TENANT_ID}}
      run: node setup-azure-auth.js