name: Setup Azure Authentication

on:
  workflow_dispatch:
    inputs:
      azure_creds:
        description: 'Azure credentials JSON'
        required: true

permissions:
  id-token: write
  contents: write
  actions: write
  packages: write
  repository-projects: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Parse Azure credentials
      id: creds
      run: |
        echo '${{github.event.inputs.azure_creds}}' > creds.json
        echo "CLIENT_ID=$(jq -r .clientId creds.json)" >> $GITHUB_ENV
        echo "CLIENT_SECRET=$(jq -r .clientSecret creds.json)" >> $GITHUB_ENV
        echo "TENANT_ID=$(jq -r .tenantId creds.json)" >> $GITHUB_ENV
        echo "SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)" >> $GITHUB_ENV
        rm creds.json

    - name: Install dependencies
      run: npm install

    - name: Debug environment
      run: |
        echo "Checking environment variables..."
        if [ -n "${{ secrets.GH_PAT }}" ]; then
          echo "GH_PAT is set"
        else
          echo "GH_PAT is not set"
        fi
        
        if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
          echo "GITHUB_TOKEN is set"
        else
          echo "GITHUB_TOKEN is not set"
        fi

    - name: Run setup script
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        AZURE_CLIENT_ID: ${{env.CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{env.CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{env.TENANT_ID}}
        AZURE_SUBSCRIPTION_ID: ${{env.SUBSCRIPTION_ID}}
      run: |
        echo "Setting up Azure authentication..."
        node setup-azure-auth.js
