name: Deploy Frontend to Azure (F1 Tier)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - '.github/workflows/azure-deploy-optimized.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: buddy-chat-app
  AZURE_RESOURCE_GROUP: chat-app-frontend-rg
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_FRONTEND_SUBSCRIPTION_ID }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-client:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    # Install and build client (optimized with chunking)
    - name: Build client
      run: |
        echo "Installing dependencies..."
        npm ci --prefer-offline --no-audit

        echo "Building client in production mode..."
        export NODE_OPTIONS="--max-old-space-size=4096"
        npm run build

        echo "Optimizing build output..."
        find build -type f -name "*.map" -delete
        find build -type f -name "*.txt" -delete
        find build -type f -name "LICENSE*" -delete
        find build -type f -name "asset-manifest.json" -delete

    # Package frontend (optimized for F1 tier)
    - name: Package frontend
      run: |
        echo "Packaging frontend..."
        cd build
        # Only include essential files
        zip -r ../frontend.zip . -x "*.map" "*.txt" "*.md"

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend.zip
        retention-days: 1

  deploy:
    needs: [build-client]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: ${{ format('https://{0}.azurewebsites.net', env.AZURE_WEBAPP_NAME) }}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: .

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_FRONTEND_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_FRONTEND_SUBSCRIPTION_ID }}

    - name: Deploy application
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Deploy with zip package (optimized for F1 tier)
          echo "Deploying frontend..."
          
          # Function to deploy with retries
          deploy_with_retries() {
            local max_attempts=3
            local attempt=1
            local delay=30
            
            while [ $attempt -le $max_attempts ]; do
              echo "Deployment attempt $attempt of $max_attempts..."
              
              az webapp deploy \
                --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                --name ${{ env.AZURE_WEBAPP_NAME }} \
                --src-path "frontend.zip" \
                --type zip \
                --async true \
                --restart true \
                --timeout 300 && return 0
              
              echo "Deployment failed, waiting ${delay}s before retry..."
              sleep $delay
              attempt=$((attempt + 1))
              delay=$((delay * 2))
            done
            
            return 1
          }
          
          deploy_with_retries
          
          # Configure app settings and web app
          echo "Configuring web app settings..."
          
          # Update minimal app settings for F1 tier
          az webapp config appsettings set \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=false \
              WEBSITE_NODE_DEFAULT_VERSION=18-lts \
              WEBSITE_RUN_FROM_PACKAGE=1 \
              WEBSITE_MEMORY_LIMIT_MB=128 \
              NODE_OPTIONS="--max-old-space-size=128" \
              NODE_ENV=production

  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_FRONTEND_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_FRONTEND_SUBSCRIPTION_ID }}

    - name: Health Check
      run: |
        check_health() {
          local url=$1
          local name=$2
          local max_retries=5
          local retry_delay=30
          local retry=0
          
          while [ $retry -lt $max_retries ]; do
            status=$(curl -sL -o /dev/null -w "%{http_code}" $url || echo "000")
            if [ "$status" = "200" ]; then
              echo "$name is healthy (Status: $status)"
              return 0
            fi
            
            echo "$name not ready (Status: $status), retrying in ${retry_delay}s... (Attempt $((retry+1))/$max_retries)"
            sleep $retry_delay
            retry=$((retry+1))
          done
          
          echo "$name failed health check after $max_retries attempts"
          return 1
        }

        check_health "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" "${{ env.AZURE_WEBAPP_NAME }}"
