name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        CI: false # Prevents treating warnings as errors

    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: buddy-chat-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./build

    - name: Deploy Backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: chat-app-backend-123
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: ./server

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: chat-app-backend-123
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        app-settings-json: |
          [
            {
              "name": "COSMOS_DB_CONNECTION_STRING",
              "value": "${{ secrets.COSMOS_DB_CONNECTION_STRING }}"
            },
            {
              "name": "REDIS_CONNECTION_STRING",
              "value": "${{ secrets.REDIS_CONNECTION_STRING }}"
            },
            {
              "name": "NODE_ENV",
              "value": "production"
            }
          ]
